//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace MvcEntretenimiento.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ServiceEntretenimiento", Namespace="http://tempuri.org/")]
    public partial class ServiceEntretenimiento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegistrarCabeceraCampoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarServicioCampoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerClubsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerJuegosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveOfertaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceEntretenimiento() {
            this.Url = global::MvcEntretenimiento.Properties.Settings.Default.MvcEntretenimiento_localhost_ServiceEntretenimiento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistrarCabeceraCampoCompletedEventHandler RegistrarCabeceraCampoCompleted;
        
        /// <remarks/>
        public event RegistrarServicioCampoCompletedEventHandler RegistrarServicioCampoCompleted;
        
        /// <remarks/>
        public event LeerClubsCompletedEventHandler LeerClubsCompleted;
        
        /// <remarks/>
        public event LeerJuegosCompletedEventHandler LeerJuegosCompleted;
        
        /// <remarks/>
        public event LeerServiciosCompletedEventHandler LeerServiciosCompleted;
        
        /// <remarks/>
        public event ReceiveOfertaCompletedEventHandler ReceiveOfertaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/RegistrarCabeceraCampo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarCabeceraCampo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BESolicitudCampo besolicitudcampo, out int RegistrarCabeceraCampoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RegistrarCabeceraCampoResultSpecified) {
            object[] results = this.Invoke("RegistrarCabeceraCampo", new object[] {
                        besolicitudcampo});
            RegistrarCabeceraCampoResult = ((int)(results[0]));
            RegistrarCabeceraCampoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void RegistrarCabeceraCampoAsync(BESolicitudCampo besolicitudcampo) {
            this.RegistrarCabeceraCampoAsync(besolicitudcampo, null);
        }
        
        /// <remarks/>
        public void RegistrarCabeceraCampoAsync(BESolicitudCampo besolicitudcampo, object userState) {
            if ((this.RegistrarCabeceraCampoOperationCompleted == null)) {
                this.RegistrarCabeceraCampoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarCabeceraCampoOperationCompleted);
            }
            this.InvokeAsync("RegistrarCabeceraCampo", new object[] {
                        besolicitudcampo}, this.RegistrarCabeceraCampoOperationCompleted, userState);
        }
        
        private void OnRegistrarCabeceraCampoOperationCompleted(object arg) {
            if ((this.RegistrarCabeceraCampoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarCabeceraCampoCompleted(this, new RegistrarCabeceraCampoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/RegistrarServicioCampo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarServicioCampo([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")] BEServicioCampo[] listbeserviciocampo) {
            this.Invoke("RegistrarServicioCampo", new object[] {
                        listbeserviciocampo});
        }
        
        /// <remarks/>
        public void RegistrarServicioCampoAsync(BEServicioCampo[] listbeserviciocampo) {
            this.RegistrarServicioCampoAsync(listbeserviciocampo, null);
        }
        
        /// <remarks/>
        public void RegistrarServicioCampoAsync(BEServicioCampo[] listbeserviciocampo, object userState) {
            if ((this.RegistrarServicioCampoOperationCompleted == null)) {
                this.RegistrarServicioCampoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarServicioCampoOperationCompleted);
            }
            this.InvokeAsync("RegistrarServicioCampo", new object[] {
                        listbeserviciocampo}, this.RegistrarServicioCampoOperationCompleted, userState);
        }
        
        private void OnRegistrarServicioCampoOperationCompleted(object arg) {
            if ((this.RegistrarServicioCampoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarServicioCampoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/LeerClubs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
        public BEClub[] LeerClubs() {
            object[] results = this.Invoke("LeerClubs", new object[0]);
            return ((BEClub[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerClubsAsync() {
            this.LeerClubsAsync(null);
        }
        
        /// <remarks/>
        public void LeerClubsAsync(object userState) {
            if ((this.LeerClubsOperationCompleted == null)) {
                this.LeerClubsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerClubsOperationCompleted);
            }
            this.InvokeAsync("LeerClubs", new object[0], this.LeerClubsOperationCompleted, userState);
        }
        
        private void OnLeerClubsOperationCompleted(object arg) {
            if ((this.LeerClubsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerClubsCompleted(this, new LeerClubsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/LeerJuegos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
        public BEJuego[] LeerJuegos() {
            object[] results = this.Invoke("LeerJuegos", new object[0]);
            return ((BEJuego[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerJuegosAsync() {
            this.LeerJuegosAsync(null);
        }
        
        /// <remarks/>
        public void LeerJuegosAsync(object userState) {
            if ((this.LeerJuegosOperationCompleted == null)) {
                this.LeerJuegosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerJuegosOperationCompleted);
            }
            this.InvokeAsync("LeerJuegos", new object[0], this.LeerJuegosOperationCompleted, userState);
        }
        
        private void OnLeerJuegosOperationCompleted(object arg) {
            if ((this.LeerJuegosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerJuegosCompleted(this, new LeerJuegosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/LeerServicios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
        public BEServicio[] LeerServicios() {
            object[] results = this.Invoke("LeerServicios", new object[0]);
            return ((BEServicio[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerServiciosAsync() {
            this.LeerServiciosAsync(null);
        }
        
        /// <remarks/>
        public void LeerServiciosAsync(object userState) {
            if ((this.LeerServiciosOperationCompleted == null)) {
                this.LeerServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerServiciosOperationCompleted);
            }
            this.InvokeAsync("LeerServicios", new object[0], this.LeerServiciosOperationCompleted, userState);
        }
        
        private void OnLeerServiciosOperationCompleted(object arg) {
            if ((this.LeerServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerServiciosCompleted(this, new LeerServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServiceEntretenimiento/ReceiveOferta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
        public BEOferta[] ReceiveOferta() {
            object[] results = this.Invoke("ReceiveOferta", new object[0]);
            return ((BEOferta[])(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveOfertaAsync() {
            this.ReceiveOfertaAsync(null);
        }
        
        /// <remarks/>
        public void ReceiveOfertaAsync(object userState) {
            if ((this.ReceiveOfertaOperationCompleted == null)) {
                this.ReceiveOfertaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveOfertaOperationCompleted);
            }
            this.InvokeAsync("ReceiveOferta", new object[0], this.ReceiveOfertaOperationCompleted, userState);
        }
        
        private void OnReceiveOfertaOperationCompleted(object arg) {
            if ((this.ReceiveOfertaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveOfertaCompleted(this, new ReceiveOfertaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BESolicitudCampo {
        
        private int coClubField;
        
        private bool coClubFieldSpecified;
        
        private int coResponsableField;
        
        private bool coResponsableFieldSpecified;
        
        private System.DateTime feDiaCampoField;
        
        private bool feDiaCampoFieldSpecified;
        
        private int nuTotalPersonasField;
        
        private bool nuTotalPersonasFieldSpecified;
        
        /// <remarks/>
        public int CoClub {
            get {
                return this.coClubField;
            }
            set {
                this.coClubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoClubSpecified {
            get {
                return this.coClubFieldSpecified;
            }
            set {
                this.coClubFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CoResponsable {
            get {
                return this.coResponsableField;
            }
            set {
                this.coResponsableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoResponsableSpecified {
            get {
                return this.coResponsableFieldSpecified;
            }
            set {
                this.coResponsableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FeDiaCampo {
            get {
                return this.feDiaCampoField;
            }
            set {
                this.feDiaCampoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeDiaCampoSpecified {
            get {
                return this.feDiaCampoFieldSpecified;
            }
            set {
                this.feDiaCampoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NuTotalPersonas {
            get {
                return this.nuTotalPersonasField;
            }
            set {
                this.nuTotalPersonasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NuTotalPersonasSpecified {
            get {
                return this.nuTotalPersonasFieldSpecified;
            }
            set {
                this.nuTotalPersonasFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BEOferta {
        
        private long coOfertaField;
        
        private bool coOfertaFieldSpecified;
        
        private string descripcionField;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        public long CoOferta {
            get {
                return this.coOfertaField;
            }
            set {
                this.coOfertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoOfertaSpecified {
            get {
                return this.coOfertaFieldSpecified;
            }
            set {
                this.coOfertaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BEServicio {
        
        private int coServicioField;
        
        private bool coServicioFieldSpecified;
        
        private string txtDescripcionField;
        
        /// <remarks/>
        public int CoServicio {
            get {
                return this.coServicioField;
            }
            set {
                this.coServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoServicioSpecified {
            get {
                return this.coServicioFieldSpecified;
            }
            set {
                this.coServicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TxtDescripcion {
            get {
                return this.txtDescripcionField;
            }
            set {
                this.txtDescripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BEJuego {
        
        private int coJuegoField;
        
        private bool coJuegoFieldSpecified;
        
        private string txtDescripcionField;
        
        /// <remarks/>
        public int CoJuego {
            get {
                return this.coJuegoField;
            }
            set {
                this.coJuegoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoJuegoSpecified {
            get {
                return this.coJuegoFieldSpecified;
            }
            set {
                this.coJuegoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TxtDescripcion {
            get {
                return this.txtDescripcionField;
            }
            set {
                this.txtDescripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BEClub {
        
        private int coClubField;
        
        private bool coClubFieldSpecified;
        
        private string noClubField;
        
        /// <remarks/>
        public int CoClub {
            get {
                return this.coClubField;
            }
            set {
                this.coClubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoClubSpecified {
            get {
                return this.coClubFieldSpecified;
            }
            set {
                this.coClubFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NoClub {
            get {
                return this.noClubField;
            }
            set {
                this.noClubField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    public partial class BEServicioCampo {
        
        private int coDiaCampoField;
        
        private bool coDiaCampoFieldSpecified;
        
        private System.Nullable<int> coJuegoField;
        
        private bool coJuegoFieldSpecified;
        
        private int coResponsableField;
        
        private bool coResponsableFieldSpecified;
        
        private System.Nullable<int> coServicioField;
        
        private bool coServicioFieldSpecified;
        
        private string nameServicioField;
        
        private int nuPersonasField;
        
        private bool nuPersonasFieldSpecified;
        
        private int nuSecuenciaField;
        
        private bool nuSecuenciaFieldSpecified;
        
        private decimal ssImporteField;
        
        private bool ssImporteFieldSpecified;
        
        private decimal ssPrecioPersonaField;
        
        private bool ssPrecioPersonaFieldSpecified;
        
        private string txtComentarioField;
        
        /// <remarks/>
        public int CoDiaCampo {
            get {
                return this.coDiaCampoField;
            }
            set {
                this.coDiaCampoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoDiaCampoSpecified {
            get {
                return this.coDiaCampoFieldSpecified;
            }
            set {
                this.coDiaCampoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CoJuego {
            get {
                return this.coJuegoField;
            }
            set {
                this.coJuegoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoJuegoSpecified {
            get {
                return this.coJuegoFieldSpecified;
            }
            set {
                this.coJuegoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CoResponsable {
            get {
                return this.coResponsableField;
            }
            set {
                this.coResponsableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoResponsableSpecified {
            get {
                return this.coResponsableFieldSpecified;
            }
            set {
                this.coResponsableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CoServicio {
            get {
                return this.coServicioField;
            }
            set {
                this.coServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoServicioSpecified {
            get {
                return this.coServicioFieldSpecified;
            }
            set {
                this.coServicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameServicio {
            get {
                return this.nameServicioField;
            }
            set {
                this.nameServicioField = value;
            }
        }
        
        /// <remarks/>
        public int NuPersonas {
            get {
                return this.nuPersonasField;
            }
            set {
                this.nuPersonasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NuPersonasSpecified {
            get {
                return this.nuPersonasFieldSpecified;
            }
            set {
                this.nuPersonasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NuSecuencia {
            get {
                return this.nuSecuenciaField;
            }
            set {
                this.nuSecuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NuSecuenciaSpecified {
            get {
                return this.nuSecuenciaFieldSpecified;
            }
            set {
                this.nuSecuenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SsImporte {
            get {
                return this.ssImporteField;
            }
            set {
                this.ssImporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SsImporteSpecified {
            get {
                return this.ssImporteFieldSpecified;
            }
            set {
                this.ssImporteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SsPrecioPersona {
            get {
                return this.ssPrecioPersonaField;
            }
            set {
                this.ssPrecioPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SsPrecioPersonaSpecified {
            get {
                return this.ssPrecioPersonaFieldSpecified;
            }
            set {
                this.ssPrecioPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TxtComentario {
            get {
                return this.txtComentarioField;
            }
            set {
                this.txtComentarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegistrarCabeceraCampoCompletedEventHandler(object sender, RegistrarCabeceraCampoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarCabeceraCampoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarCabeceraCampoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int RegistrarCabeceraCampoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool RegistrarCabeceraCampoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegistrarServicioCampoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LeerClubsCompletedEventHandler(object sender, LeerClubsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerClubsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerClubsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEClub[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEClub[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LeerJuegosCompletedEventHandler(object sender, LeerJuegosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerJuegosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerJuegosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEJuego[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEJuego[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LeerServiciosCompletedEventHandler(object sender, LeerServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEServicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEServicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReceiveOfertaCompletedEventHandler(object sender, ReceiveOfertaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveOfertaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveOfertaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEOferta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEOferta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591