'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3053
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Menu_Principal.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _NEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_NEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property campo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property campo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property campo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cliente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cliente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Compuplaza2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compuplaza2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compuplaza3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compuplaza3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compuplaza4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compuplaza4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property em110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("em110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo_3d_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_3d_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo_campo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_campo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesjjjkkkl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesjjjkkkl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesytyu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesytyu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LEAF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LEAF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ljkli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ljkli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property POINT06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("POINT06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property REPO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property REPO2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPO2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property REPO3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPO3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usu_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usu_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usu_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usu_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usuario_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usuario_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
