//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public long CoCtl { get; set; }
        public int CoSubCtl { get; set; }
        public string NoDescripcion { get; set; }
    
        public virtual master_catalogo master_catalogo { get; set; }
    }
}
