//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class club
    {
        public club()
        {
            this.solicitud_dia_campo = new HashSet<solicitud_dia_campo>();
        }
    
        public long CoClub { get; set; }
        public string NoClub { get; set; }
        public string NoDireccion { get; set; }
    
        public virtual ICollection<solicitud_dia_campo> solicitud_dia_campo { get; set; }
    }
}
