//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_dia_campo
    {
        public long CoDiaCampo { get; set; }
        public long CoResponsable { get; set; }
        public int NuSecuencia { get; set; }
        public Nullable<int> NuPersonas { get; set; }
        public Nullable<decimal> SsPrecioPersona { get; set; }
        public Nullable<decimal> SsImporte { get; set; }
        public string TxtComentario { get; set; }
        public long CoServicio { get; set; }
        public long CoJuego { get; set; }
    
        public virtual juego juego { get; set; }
        public virtual servicio servicio { get; set; }
        public virtual solicitud_dia_campo solicitud_dia_campo { get; set; }
    }
}
