//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleoferta
    {
        public long CoOferta { get; set; }
        public int NuSecuencia { get; set; }
        public Nullable<System.DateTime> FeConsulta { get; set; }
        public string TxtConsulta { get; set; }
        public string TxtRespuesta { get; set; }
        public long CoResponsable { get; set; }
        public long CoUsuarioAdmin { get; set; }
    
        public virtual oferta oferta { get; set; }
        public virtual responsable_familia responsable_familia { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
