//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.juego = new HashSet<juego>();
        }
    
        public long CoMaterial { get; set; }
        public string NoMaterial { get; set; }
    
        public virtual ICollection<juego> juego { get; set; }
    }
}
