//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta
    {
        public oferta()
        {
            this.detalleoferta = new HashSet<detalleoferta>();
            this.solicitud_dia_campo = new HashSet<solicitud_dia_campo>();
        }
    
        public long CoOferta { get; set; }
        public string NoOferta { get; set; }
        public Nullable<System.DateTime> FeInicio { get; set; }
        public Nullable<System.DateTime> FeCaducidad { get; set; }
        public string TxtDescripcion { get; set; }
        public Nullable<int> CoUbicacion { get; set; }
        public Nullable<int> FlEstado { get; set; }
    
        public virtual ICollection<detalleoferta> detalleoferta { get; set; }
        public virtual ICollection<solicitud_dia_campo> solicitud_dia_campo { get; set; }
    }
}
