//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsable_familia
    {
        public responsable_familia()
        {
            this.detalleoferta = new HashSet<detalleoferta>();
            this.solicitud_dia_campo = new HashSet<solicitud_dia_campo>();
        }
    
        public long CoResponsable { get; set; }
        public string NoNombres { get; set; }
        public string NoApePaterno { get; set; }
        public string NoApeMaterno { get; set; }
        public Nullable<int> FlSexo { get; set; }
        public Nullable<int> CoTipoDocumento { get; set; }
        public string NuDocumento { get; set; }
        public string NoDireccion { get; set; }
        public string NuCelular { get; set; }
        public Nullable<int> FlEstado { get; set; }
        public long CoUsuario { get; set; }
    
        public virtual ICollection<detalleoferta> detalleoferta { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<solicitud_dia_campo> solicitud_dia_campo { get; set; }
    }
}
