//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public servicio()
        {
            this.detalle_dia_campo = new HashSet<detalle_dia_campo>();
        }
    
        public long CoServicio { get; set; }
        public string NoServicio { get; set; }
        public string TxtDescripcion { get; set; }
        public Nullable<decimal> SsPrecio { get; set; }
        public Nullable<int> FlEstado { get; set; }
    
        public virtual ICollection<detalle_dia_campo> detalle_dia_campo { get; set; }
    }
}
