//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_dia_campo
    {
        public solicitud_dia_campo()
        {
            this.detalle_dia_campo = new HashSet<detalle_dia_campo>();
        }
    
        public long CoDiaCampo { get; set; }
        public long CoResponsable { get; set; }
        public Nullable<System.DateTime> FeDiaCampo { get; set; }
        public Nullable<int> NuTotalPersonas { get; set; }
        public Nullable<decimal> SsImporteTotal { get; set; }
        public Nullable<int> FlAprobado { get; set; }
        public Nullable<System.DateTime> FeAprobado { get; set; }
        public Nullable<long> CoUsuarioAdmin { get; set; }
        public long CoClub { get; set; }
        public Nullable<long> CoOferta { get; set; }
    
        public virtual club club { get; set; }
        public virtual ICollection<detalle_dia_campo> detalle_dia_campo { get; set; }
        public virtual oferta oferta { get; set; }
        public virtual responsable_familia responsable_familia { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
