//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.detalleoferta = new HashSet<detalleoferta>();
            this.responsable_familia = new HashSet<responsable_familia>();
            this.solicitud_dia_campo = new HashSet<solicitud_dia_campo>();
        }
    
        public long CoUsuario { get; set; }
        public Nullable<int> CoTipoUsuario { get; set; }
        public string NoEmail { get; set; }
        public Nullable<int> FlEstado { get; set; }
        public string NoContrasena { get; set; }
    
        public virtual ICollection<detalleoferta> detalleoferta { get; set; }
        public virtual ICollection<responsable_familia> responsable_familia { get; set; }
        public virtual ICollection<solicitud_dia_campo> solicitud_dia_campo { get; set; }
    }
}
