//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEntretenimientoWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BESolicitudCampo", Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    [System.SerializableAttribute()]
    public partial class BESolicitudCampo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FeDiaCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NuTotalPersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoClub {
            get {
                return this.CoClubField;
            }
            set {
                if ((this.CoClubField.Equals(value) != true)) {
                    this.CoClubField = value;
                    this.RaisePropertyChanged("CoClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoResponsable {
            get {
                return this.CoResponsableField;
            }
            set {
                if ((this.CoResponsableField.Equals(value) != true)) {
                    this.CoResponsableField = value;
                    this.RaisePropertyChanged("CoResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FeDiaCampo {
            get {
                return this.FeDiaCampoField;
            }
            set {
                if ((this.FeDiaCampoField.Equals(value) != true)) {
                    this.FeDiaCampoField = value;
                    this.RaisePropertyChanged("FeDiaCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NuTotalPersonas {
            get {
                return this.NuTotalPersonasField;
            }
            set {
                if ((this.NuTotalPersonasField.Equals(value) != true)) {
                    this.NuTotalPersonasField = value;
                    this.RaisePropertyChanged("NuTotalPersonas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEServicioCampo", Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    [System.SerializableAttribute()]
    public partial class BEServicioCampo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoDiaCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoJuegoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NuPersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NuSecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SsImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SsPrecioPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtComentarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoDiaCampo {
            get {
                return this.CoDiaCampoField;
            }
            set {
                if ((this.CoDiaCampoField.Equals(value) != true)) {
                    this.CoDiaCampoField = value;
                    this.RaisePropertyChanged("CoDiaCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoJuego {
            get {
                return this.CoJuegoField;
            }
            set {
                if ((this.CoJuegoField.Equals(value) != true)) {
                    this.CoJuegoField = value;
                    this.RaisePropertyChanged("CoJuego");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoResponsable {
            get {
                return this.CoResponsableField;
            }
            set {
                if ((this.CoResponsableField.Equals(value) != true)) {
                    this.CoResponsableField = value;
                    this.RaisePropertyChanged("CoResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoServicio {
            get {
                return this.CoServicioField;
            }
            set {
                if ((this.CoServicioField.Equals(value) != true)) {
                    this.CoServicioField = value;
                    this.RaisePropertyChanged("CoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameServicio {
            get {
                return this.NameServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.NameServicioField, value) != true)) {
                    this.NameServicioField = value;
                    this.RaisePropertyChanged("NameServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NuPersonas {
            get {
                return this.NuPersonasField;
            }
            set {
                if ((this.NuPersonasField.Equals(value) != true)) {
                    this.NuPersonasField = value;
                    this.RaisePropertyChanged("NuPersonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NuSecuencia {
            get {
                return this.NuSecuenciaField;
            }
            set {
                if ((this.NuSecuenciaField.Equals(value) != true)) {
                    this.NuSecuenciaField = value;
                    this.RaisePropertyChanged("NuSecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SsImporte {
            get {
                return this.SsImporteField;
            }
            set {
                if ((this.SsImporteField.Equals(value) != true)) {
                    this.SsImporteField = value;
                    this.RaisePropertyChanged("SsImporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SsPrecioPersona {
            get {
                return this.SsPrecioPersonaField;
            }
            set {
                if ((this.SsPrecioPersonaField.Equals(value) != true)) {
                    this.SsPrecioPersonaField = value;
                    this.RaisePropertyChanged("SsPrecioPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtComentario {
            get {
                return this.TxtComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtComentarioField, value) != true)) {
                    this.TxtComentarioField = value;
                    this.RaisePropertyChanged("TxtComentario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEClub", Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    [System.SerializableAttribute()]
    public partial class BEClub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoClubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoClub {
            get {
                return this.CoClubField;
            }
            set {
                if ((this.CoClubField.Equals(value) != true)) {
                    this.CoClubField = value;
                    this.RaisePropertyChanged("CoClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoClub {
            get {
                return this.NoClubField;
            }
            set {
                if ((object.ReferenceEquals(this.NoClubField, value) != true)) {
                    this.NoClubField = value;
                    this.RaisePropertyChanged("NoClub");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEJuego", Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    [System.SerializableAttribute()]
    public partial class BEJuego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoJuegoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoJuego {
            get {
                return this.CoJuegoField;
            }
            set {
                if ((this.CoJuegoField.Equals(value) != true)) {
                    this.CoJuegoField = value;
                    this.RaisePropertyChanged("CoJuego");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtDescripcion {
            get {
                return this.TxtDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtDescripcionField, value) != true)) {
                    this.TxtDescripcionField = value;
                    this.RaisePropertyChanged("TxtDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEServicio", Namespace="http://schemas.datacontract.org/2004/07/BEEntities")]
    [System.SerializableAttribute()]
    public partial class BEServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoServicio {
            get {
                return this.CoServicioField;
            }
            set {
                if ((this.CoServicioField.Equals(value) != true)) {
                    this.CoServicioField = value;
                    this.RaisePropertyChanged("CoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtDescripcion {
            get {
                return this.TxtDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtDescripcionField, value) != true)) {
                    this.TxtDescripcionField = value;
                    this.RaisePropertyChanged("TxtDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceEntretenimiento")]
    public interface ServiceEntretenimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/RegistrarCabeceraCampo", ReplyAction="http://tempuri.org/ServiceEntretenimiento/RegistrarCabeceraCampoResponse")]
        int RegistrarCabeceraCampo(MvcEntretenimientoWeb.ServiceReference1.BESolicitudCampo besolicitudcampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/RegistrarCabeceraCampo", ReplyAction="http://tempuri.org/ServiceEntretenimiento/RegistrarCabeceraCampoResponse")]
        System.Threading.Tasks.Task<int> RegistrarCabeceraCampoAsync(MvcEntretenimientoWeb.ServiceReference1.BESolicitudCampo besolicitudcampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/RegistrarServicioCampo", ReplyAction="http://tempuri.org/ServiceEntretenimiento/RegistrarServicioCampoResponse")]
        void RegistrarServicioCampo(MvcEntretenimientoWeb.ServiceReference1.BEServicioCampo[] listbeserviciocampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/RegistrarServicioCampo", ReplyAction="http://tempuri.org/ServiceEntretenimiento/RegistrarServicioCampoResponse")]
        System.Threading.Tasks.Task RegistrarServicioCampoAsync(MvcEntretenimientoWeb.ServiceReference1.BEServicioCampo[] listbeserviciocampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerClubs", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerClubsResponse")]
        MvcEntretenimientoWeb.ServiceReference1.BEClub[] LeerClubs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerClubs", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerClubsResponse")]
        System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEClub[]> LeerClubsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerJuegos", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerJuegosResponse")]
        MvcEntretenimientoWeb.ServiceReference1.BEJuego[] LeerJuegos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerJuegos", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerJuegosResponse")]
        System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEJuego[]> LeerJuegosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerServicios", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerServiciosResponse")]
        MvcEntretenimientoWeb.ServiceReference1.BEServicio[] LeerServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEntretenimiento/LeerServicios", ReplyAction="http://tempuri.org/ServiceEntretenimiento/LeerServiciosResponse")]
        System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEServicio[]> LeerServiciosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceEntretenimientoChannel : MvcEntretenimientoWeb.ServiceReference1.ServiceEntretenimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEntretenimientoClient : System.ServiceModel.ClientBase<MvcEntretenimientoWeb.ServiceReference1.ServiceEntretenimiento>, MvcEntretenimientoWeb.ServiceReference1.ServiceEntretenimiento {
        
        public ServiceEntretenimientoClient() {
        }
        
        public ServiceEntretenimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEntretenimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEntretenimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEntretenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarCabeceraCampo(MvcEntretenimientoWeb.ServiceReference1.BESolicitudCampo besolicitudcampo) {
            return base.Channel.RegistrarCabeceraCampo(besolicitudcampo);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarCabeceraCampoAsync(MvcEntretenimientoWeb.ServiceReference1.BESolicitudCampo besolicitudcampo) {
            return base.Channel.RegistrarCabeceraCampoAsync(besolicitudcampo);
        }
        
        public void RegistrarServicioCampo(MvcEntretenimientoWeb.ServiceReference1.BEServicioCampo[] listbeserviciocampo) {
            base.Channel.RegistrarServicioCampo(listbeserviciocampo);
        }
        
        public System.Threading.Tasks.Task RegistrarServicioCampoAsync(MvcEntretenimientoWeb.ServiceReference1.BEServicioCampo[] listbeserviciocampo) {
            return base.Channel.RegistrarServicioCampoAsync(listbeserviciocampo);
        }
        
        public MvcEntretenimientoWeb.ServiceReference1.BEClub[] LeerClubs() {
            return base.Channel.LeerClubs();
        }
        
        public System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEClub[]> LeerClubsAsync() {
            return base.Channel.LeerClubsAsync();
        }
        
        public MvcEntretenimientoWeb.ServiceReference1.BEJuego[] LeerJuegos() {
            return base.Channel.LeerJuegos();
        }
        
        public System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEJuego[]> LeerJuegosAsync() {
            return base.Channel.LeerJuegosAsync();
        }
        
        public MvcEntretenimientoWeb.ServiceReference1.BEServicio[] LeerServicios() {
            return base.Channel.LeerServicios();
        }
        
        public System.Threading.Tasks.Task<MvcEntretenimientoWeb.ServiceReference1.BEServicio[]> LeerServiciosAsync() {
            return base.Channel.LeerServiciosAsync();
        }
    }
}
